# Generated by Django 2.2.4 on 2020-05-17 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_value', models.CharField(max_length=20)),
                ('deck_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CardPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_pool_key', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('session_key', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCardPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Card')),
                ('pool_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='game.CardPool')),
                ('session_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_cards', to='game.GameSession')),
            ],
        ),
        migrations.AddField(
            model_name='cardpool',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_pools', to='game.GameSession'),
        ),
    ]
