# Generated by Django 2.2.4 on 2020-04-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('table_code', models.CharField(max_length=8)),
                ('private', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='GameTable',
        ),
    ]
