# Generated by Django 2.2.4 on 2020-04-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_auto_20200403_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameroom',
            old_name='table_code',
            new_name='room_code',
        ),
    ]
